name: Overlay
main: OP\Main
version: "1.0.0"
api: [1.0.0]
author: GannicusCoC

commands:
  overlay:
    permission: lc.overlay
    description: "Envoie un message."

permissions:
  lc.overlay:
    default: op
    description: Allow /overlay
